### ISSUE TITLE
Channel's subscriptions to onMessageAdded and onMessageDeleted not called on iOS

### ISSUE THREAD

**Issue by hugomc92** [Diversido/flutter_twilio_conversations#31]
It's working fine on Android but on Android it doesn't call the flutter implementation when listen to them

Version 1.1.7+9

Example:

```
channel.onMessageAdded?.listen((message) async {
        console.log('_generateConversation channel.onMessageAdded', channel.sid);

        // Not being called on iOS
}),

channel.onMessageDeleted?.listen((message) async {
        console.log('_generateConversation channel.onMessageDeleted', channel.sid);

        // Not being called on iOS
}),
```

**Comment by asmodeoux** [comment]
Should be solved in a 2.0.1 quickfix, closing

**Comment by hugomc92** [comment]
Hello @asmodeoux 

It's not completely fixed yet.

Now it's being called sometimes and others no, same code, same circumstances, so I can't know why sometimes the listeners are being called and others not.

Thanks in advance for your review

**Comment by martintrollip** [comment]
@hugomc92,  you can try to add this and listen for the channel to be synchronized on IOS

```dart
/// Listen to Twilio client synchronization events
client.onClientSynchronization?.listen((status) {
      if (_isSynced(status)) {
               /// subscribe to channel.onMessageAdded and channel.onMessageDeleted
      }
}

bool _isSynced(ChatClientSynchronizationStatus status) {
    return status == ChatClientSynchronizationStatus.CONVERSATIONS_COMPLETED ||
        (status == ChatClientSynchronizationStatus.COMPLETED && client.channelsInitialized());
}
````

**Comment by martintrollip** [comment]
For the `channelsInitialized` you can check that the client channels is not null. 

```dart
client?.channels != null
```

From the example code, it looks like Android and IOS handles initialization slightly differently,

See the example in `subscriptions_middleware.dart`: 

```dart
store.state.chatClient?.onClientSynchronization?.listen((event) async {
        // in Android there is a separate event to identify when fully initialized
        // in iOS we do check manually
        if (event == ChatClientSynchronizationStatus.CONVERSATIONS_COMPLETED ||
            (event == ChatClientSynchronizationStatus.COMPLETED &&
                store.state.chatClient?.channels != null)) {
                    ....
        }
```

**Comment by hugomc92** [comment]
Hello @martintrollip 

Thanks for your reply. I was actually checking the channels was not null before subscribing.

Anyways I tried your full solution and the problem still persists. There’s sometime the listeners are being fired and other not on iOS. On Android it works perfect.

Thanks for your replies

**Comment by martintrollip** [comment]
Hi @hugomc92,

We only used this during initialisation:

1. `final client = await _conversationsDatasource.create(token);` 
2. `client?.onClientSynchronization?.listen(....)` (as above) 

Any other checks and listeners on channels / messages will only happen once the client sent the synchronisation status.  

Other than this I'm not sure how to reproduce the issue for further investigations

**Comment by jullicer** [comment]
Any update to this bug? i have issue with the LAST_CONSUMED_MESSAGE_INDEX either from channel or member update.

` ChannelListener.onMemberUpdated => memberSid = MBd47ae420b5764ab4b7581a54ceb880ee, reason = LAST_READ_MESSAGE_INDEX
D/TwilioInfo(14167): ChannelListener.onMemberUpdated => memberSid = MBd47ae420b5764ab4b7581a54ceb880ee, reason = LAST_READ_MESSAGE_INDEX
D/TwilioInfo(14167): ChannelListener.onMemberUpdated => memberSid = MBd47ae420b5764ab4b7581a54ceb880ee, reason = LAST_READ_MESSAGE_INDEX
D/TwilioInfo(14167): ChannelListener.onMemberUpdated => memberSid = MBd47ae420b5764ab4b7581a54ceb880ee, reason = LAST_READ_MESSAGE_INDEX
D/TwilioInfo(14167): ChannelListener.onMemberUpdated => memberSid = MBd47ae420b5764ab4b7581a54ceb880ee, reason = LAST_READ_MESSAGE_INDEX
D/TwilioInfo(14167): ChannelListener.onMemberUpdated => memberSid = MBd47ae420b5764ab4b7581a54ceb880ee, reason = LAST_READ_MESSAGE_INDEX
D/TwilioInfo(14167): ChannelListener.onMemberUpdated => memberSid = MBd47ae420b5764ab4b7581a54ceb880ee, reason = LAST_READ_MESSAGE_INDEX`
