### ISSUE TITLE
MissingPluginException(No implementation found for method create on channel flutter_twilio_conversations)

### ISSUE THREAD

**Issue by hugomc92** [Diversido/flutter_twilio_conversations#32]
Latest version (2.0.0+10) breaks the app, indicating that there is no plugin implementation for Android and iOS.

```
I/flutter ( 4709): capturedException exception : MissingPluginException(No implementation found for method create on channel flutter_twilio_conversations)
I/flutter ( 4709): capturedException stackTrace : #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
I/flutter ( 4709): <asynchronous suspension>
I/flutter ( 4709): #1      TwilioConversationsClient.create (package:flutter_twilio_conversations/src/conversations_client.dart:71:26)
```

**Comment by asmodeoux** [comment]
@NicParmee-Kena can you review please?

**Comment by NicParmee-Kena** [comment]
Hi @hugomc92 could you please do a full clean and then run dart pub get. That should fix the problem as I look into why this is being caused.

**Comment by hugomc92** [comment]
Hi  @NicParmee-Kena 

Thanks for your reply and advice.

I've already done `flutter clean` in the hole project and I'm still getting the same problem on both, Android and iOS

**Comment by NicParmee-Kena** [comment]
Hi @hugomc92, thanks very much for reporting the issue, I have found the problem. 

It occurred just before we merged and when I updated the dependencies from local paths and needed to configure the correct packages for android and ios.

Will get the PR up as soon as possible.

**Comment by asmodeoux** [comment]
Thanks @NicParmee-Kena!
Merged and released as 2.0.1 ✅
Please close the issue once you verify it's fixed

**Comment by hugomc92** [comment]
Now it fixes on version 2.0.1! Thanks very much!
